on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release By Tag

jobs:
  version:
     name: change version
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: changeversion
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm version ${{ github.ref }} --no-git-tag-version --allow-same-version
      - run: git commit -a -m 'change version ${{ github.ref }}' && git push
