name: publish release changlog

on:
  push:
    branches:
      - release-it

jobs:
  release-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: TheRealWaldo/release-it@v0.2.1
